### ISSUE TITLE
☝ Version 1.0

### ISSUE THREAD

**Issue by emagdalenaC2i** [mbartlett21/weld-featurescript#2]
Here we can comment and define all the improvements to add in the version 1.0

# **Todo**

- [x] Add License tab ( #67 ) ( @mbartlett21 )
- [x] Update FS version ( #66 ) ( @mbartlett21 )
- [x] Add PDF tab with the description ( @mbartlett21 )
- [x] Review the code ( #4 ) ( @emagdalenaC2i )
- [x] Nicer round corner ( #13 ) (@emagdalenaC2i )
- [x] Non-planar to non-planar notification ( #6, #7 ) ( @mbartlett21 )
- [x] Add Square butt joint ( #23 ) ( @emagdalenaC2i )
- [x] Add U butt joint ( #58 ) (@emagdalenaC2i )
- [x] Add J butt joint ( #51 ) ( @emagdalenaC2i )
- [x] Add Bevel butt joint (#46) ( @emagdalenaC2i )
- [x] Add Square butt joint inclined (with angle) ( #60 ) ( @emagdalenaC2i )
- [x] Add Flat Fillet shape ( #21 ) ( @emagdalenaC2i )
- [x] Butt joints in the other side ( #24 ) ( @emagdalenaC2i )
- [x] Butt joints with several edges ( #25 ) ( @emagdalenaC2i )

![captura01](https://user-images.githubusercontent.com/24428859/49329781-e3bb6f00-f584-11e8-8bfc-7f8a03ced0d4.PNG)

# **Notes**
- To reference another developer, use @
- To reference another Issue or Pull Request use # or Username / Repository #

**Comment by emagdalenaC2i** [comment]
MIT license?? What do you think?

**Comment by mbartlett21** [comment]
Here's Onshape's:
https://cad.onshape.com/documents/12312312345abcabcabcdeff/w/a855e4161c814f2e9ab3698a/e/9c1fe3c68aae462f90b44036 :)

**Comment by mbartlett21** [comment]
You can add a license tab into Onshape (You have edit access)

**Comment by ula-w** [comment]
MIT licence is fine to us.

**Comment by ula-w** [comment]
We would like this feature not only to create weld connections but also to help constructor to choose weld type according to guidelines of production plant / welding technology.
User chooses where weld connections should be and shows thickness of welded plate, and he can choose from weld types which are feasible (for example square butt joint can be made for plate thickness 1-3mm, double square butt joint for plate thickness 2-5mm, V butt joint 3-20mm, U butt joint 15-40, so if plate thickness is 18mm user can choose from V butt joint and U butt joint not square butt joint; similar conditions are for inclined plates)
We would like this boundary conditions to be stored in csv file - we think it will be easier to adjust them for different companies. It would be great if we could have few of them in one custom feature, because there are different boundary conditions for different welding methods (user would choose method first).

**Comment by ula-w** [comment]
If you don't have access to boundary conditions and bevel dimensions I can prepare some based on these which we use.

**Comment by emagdalenaC2i** [comment]
@ula-w That's one of the reason why I add the settings tab in the feature.
The idea is that in the settings the user can select a csv or LookupTablePath with this boundary conditions.

Of course, @ula-w could you create a csv example?

**Comment by ula-w** [comment]
Something like that:
![image](https://user-images.githubusercontent.com/45488807/49432407-e6e67300-f7af-11e8-8271-fa5ac4b5b421.png)

where:
![image](https://user-images.githubusercontent.com/45488807/49432431-f4036200-f7af-11e8-8d67-f813d5e8b6ea.png)
angle in file is half of alpha = beta:
![image](https://user-images.githubusercontent.com/45488807/49432471-10070380-f7b0-11e8-97f1-8c5fe2a06e75.png)
![image](https://user-images.githubusercontent.com/45488807/49432499-20b77980-f7b0-11e8-8f42-051c2c4f1b46.png)
![image](https://user-images.githubusercontent.com/45488807/49432521-3462e000-f7b0-11e8-9745-9ee8913c6c2d.png)

With putting this to feature script I will need some help. I know how to upload csv file to feature script, but I don't know how to look in there for right parameters.

**Comment by emagdalenaC2i** [comment]
@mbartlett21 I have created a Part Studio in the Onshape document https://cad.onshape.com/documents/7c7042b84e1ae5b391af796f/w/78d4b9bbae61ce42dadb481d/e/852e4c1dcebea967aa403527 with a few examples of butt welds
![captura](https://user-images.githubusercontent.com/24428859/49781273-57dadd00-fd12-11e8-9510-a56358e0120c.PNG)

**Comment by emagdalenaC2i** [comment]
@mbartlett21 I have imported the LICENSE in the Onshape document.
Do you need help with the creation of the PDF file?

**Comment by emagdalenaC2i** [comment]
When the pdf file is ready you can announce this FS in the Onshape forums

**Comment by mbartlett21** [comment]
@emagdalenaC2i Here is the document on google docs: https://docs.google.com/presentation/d/1dyi7xGWN2Bh7VwtqoY4JdqveCGVojrb3F_6aFT0GuA4/view?usp=sharing
I am still working on it.

**Comment by mbartlett21** [comment]
Can you please check the document before I put it in Onshape?
@emagdalenaC2i

**Comment by emagdalenaC2i** [comment]
ok, where is it?

**Comment by emagdalenaC2i** [comment]
Ok, I got it

**Comment by emagdalenaC2i** [comment]
@mbartlett21 
Prerequisites:
Butt Welds:	One or more edges to create the weld between

**Comment by emagdalenaC2i** [comment]
The rest is fine

**Comment by mbartlett21** [comment]
Are you "Anonymous Unicorn"? :smile:

**Comment by emagdalenaC2i** [comment]
Anonymous Unicorn??

**Comment by emagdalenaC2i** [comment]
Maybe... I handle with several google accounts. But I opened the file with my own user

**Comment by mbartlett21** [comment]
That's what it says...

I have added the PDF to the Onshape document now, can you create a version?

**Comment by emagdalenaC2i** [comment]
@mbartlett21 I think it's better if we make a copy of the document and create a version, so it will not be all the previous versions (in development) available there.

**Comment by mbartlett21** [comment]
I have shared the new document with you: https://cad.onshape.com/documents/f6dc5a7ab4bd8dcd6217ba88

**Comment by emagdalenaC2i** [comment]
ok, so you can create a version 1.0 and share it in the Onshape forums ;-)

**Comment by emagdalenaC2i** [comment]
@mbartlett21 Are you in Australia, right?

**Comment by mbartlett21** [comment]
Yes

**Comment by mbartlett21** [comment]
Can you do the forum release and @mention me, please?

**Comment by mbartlett21** [comment]
I'd still rather you publish it.
( You created almost all the butt weld profiles and you completed most of the issues for this release )

**Comment by mbartlett21** [comment]
I have created a version 1.0.0 in Onshape

**Comment by emagdalenaC2i** [comment]
Done

**Comment by emagdalenaC2i** [comment]
So, we should close this issue, rigth?
